version: '3.8'

services:
  app:
    image: sammrai/mfapi:latest
    container_name: mfapi
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./config.json
        target: /app/config.json
    # 開発用
    #   - type: bind
    #     source: ./src
    #     target: /app/src
    # build: .
    # command: /bin/sh
    # tty: true
