openapi: 3.0.0
info:
  title: マネーフォワード操作API
  version: 0.0.1
  description: |
    マネーフォワードME を操作するAPIラッパーを提供。参照系は問題なく動作しますが更新系は更新結果の応答をサイトから得られないため実際に更新できているか確認が必要です。

  contact:
    url: https://github.com/sammrai/mfapi

servers:
  - url: http://192.168.32.70:3001
    description: Local server
  - url: http://localhost:3000/api
    description: Local machinie

paths:
  /accounts:
    get:
      tags: [口座]
      summary: 口座一覧
      description: 作成したカスタム口座一覧を取得できます
      responses:
        "200":
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /accounts/{accountString}/assets:
    get:
      tags: [資産]
      summary: 資産一覧
      description: 口座内の資産を一覧で取得できます
      parameters:
        - name: accountString
          description: 口座の接続文字列
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 資産一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Asset"
    post:
      tags: [資産]
      summary: 資産作成
      parameters:
        - name: accountString
          description: 口座の接続文字列
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssetPost"
      responses:
        "201":
          description: 資産を作成しました
        "400":
          description: 入力パラメータが誤っています

  /accounts/{accountString}/assets/{assetId}:
    delete:
      tags: [資産]
      summary: 資産削除
      parameters:
        - name: assetId
          description: 資産の一意識別子
          in: path
          required: true
          schema:
            type: string
        - name: accountString
          description: 口座の接続文字列
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 資産を削除しました
        "404":
          description: 削除する資産が見つかりません

components:
  schemas:
    Asset:
      type: object
      properties:
        assetId:
          type: string
          description: 資産のユニーク識別子
          example: "3GF7x1J_fYqVP90bzOT9CQ3gW-rwRV7PpNpjg1u3CEI"
        assetSubclassId:
          $ref: "#/components/schemas/AssetSubclass"
        name:
          type: string
          description: 資産名
          example: "USD/JPY"
        value:
          type: number
          format: float
          description: 資産価値
          example: 100
        entriedPrice:
          type: number
          format: float
          description: システム登録時の価格
          example: 90
          nullable: true
        entriedAt:
          type: string
          format: string
          description: システム登録日
          example: "2022/01/01"
          nullable: true
    AssetSubclass:
      type: string
      enum:
        - Cash
        - ElectronicMoney
        - OrdinaryDeposit
        - TimeDeposit
        - AccumulationTimeDeposit
        - ForeignCurrencyDeposit
        - DepositoryMoney_MRF
        - Deposit_Margin
        - Cryptocurrency
        - OtherDeposits
        - DomesticStock
        - USStock
        - ChinaStock
        - ForeignStock
        - UnlistedStock
        - OtherStocks
        - CreditMargin_Deposit
        - DomesticStock_Credit
        - USStock_Credit
        - ChinaStock_Credit
        - ForeignStock_Credit
        - OtherStocks_Credit
        - InvestmentTrust
        - ForeignInvestmentTrust
        - MidTermGovernmentBondFund
        - MMF
        - ForeignCurrencyMMF
        - OtherInvestmentTrust
        - GovernmentBond
        - CorporateBond
        - ForeignBond
        - StructuredBond
        - OtherBonds
        - SocialLending
        - FXMargin
        - OverTheCounterFX
        - Click365
        - OsakaFX
        - OtherFX
        - FuturesOPMargin
        - IndexFutures
        - IndexOP
        - CFD
        - ClickStock365
        - CommodityFutures
        - OtherFuturesOP
        - DomesticStock_StockOption
        - AccumulationTypeInsurance
        - Building_Home
        - Building_InvestmentBusiness
        - Land_Home
        - Land_InvestmentBusiness
        - NationalPension
        - WelfarePension
        - MutualAidPension
        - CorporatePension
        - WelfarePensionFund
        - NationalPensionFund
        - DefinedContributionPension
        - PrivatePension
        - Points_Miles
        - Automobile
        - PreciousMetals_Jewelry
        - OtherAssets
      description: 資産のサブクラスID
    AssetPost:
      allOf:
        - $ref: "#/components/schemas/Asset"
      required:
        - assetSubclassId
        - name
        - value
    Account:
      type: object
      properties:
        name:
          type: string
          description: 口座の名前
        id:
          type: string
          description: 口座の一意識別子
        subAccountIdHash:
          type: string
          description: 口座制御の一意識別子
        accountString:
          type: string
          description: 口座の接続文字列
