name: Build docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: |
        npx redoc-cli bundle openapi/openapi.yaml
        mv redoc-static.html index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'
        cname: docs.api.jizt.it