name: Build docs
on:
  push:
    branches:
      - main
      - build_docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: |
        npx @redocly/cli build-docs ./src/openapi.yaml -o ./src/index.html --theme.openapi.disableSearch=true --theme.openapi.expandResponses='200,201'
        mv redoc-static.html index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'
        cname: docs.api.jizt.it